// helper/customer/currencyMap.js

const currencyMap = {
    AE: "AED",
    US: "USD",
    IN: "INR",
    SA: "SAR",
    GB: "GBP",
    CA: "CAD",
    PK: "PKR",
    AU: "AUD",
    BD: "BDT",
    BH: "BHD",
    CN: "CNY",
    DE: "EUR",
    EG: "EGP",
    FR: "EUR",
    IT: "EUR",
    JP: "JPY",
    JO: "JOD",
    KE: "KES",
    KW: "KWD",
    LB: "LBP",
    MY: "MYR",
    NG: "NGN",
    NP: "NPR",
    NL: "EUR",
    NZ: "NZD",
    OM: "OMR",
    PH: "PHP",
    QA: "QAR",
    RU: "RUB",
    SG: "SGD",
    SD: "SDG",
    SE: "SEK",
    CH: "CHF",
    TR: "TRY",
    TZ: "TZS",
    UG: "UGX",
    UA: "UAH",
    VN: "VND",
    ZA: "ZAR",
    IR: "IRR",
    IQ: "IQD",
    IL: "ILS",
    KR: "KRW",
    TH: "THB",
    HK: "HKD",
    ID: "IDR",
    AR: "ARS",
    BR: "BRL",
    MX: "MXN",
    ES: "EUR",
    BE: "EUR",
    PT: "EUR",
    DK: "DKK",
    NO: "NOK",
    FI: "EUR",
    CZ: "CZK",
    PL: "PLN",
    RO: "RON",
    HU: "HUF",
    SK: "EUR"
  };
  
  export default currencyMap;
  